### ISSUE TITLE
친구 검색 미리보기 기능

### ISSUE THREAD

**Issue by comeintostout** [boostcampwm-2022/web05-SleepyWoods#123]
## 💁 설명

- 친구추가 창에서 유저 nickname 검색 시, 해당 nickname으로 시작되는 유저들 정보 미리보기

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] nickname 으로 유저 검색
- [x] API 명세 작성

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 
- [x] Query 성능 고려하기
- [x] FE에서 어떤 시점에 해당 API를 날릴 지 고려하기

**Comment by ktmihs** [comment]
참고로 frontend에서는 debounce를 걸어서 일정 시간 동안 입력하지 않았을 때, 해당 키워드를 api 요청하도록 구현했습니다!
