### ISSUE TITLE
[problem] 토큰이 없는데 데이터를 받아오는 이슈 

### ISSUE THREAD

**Issue by ktmihs** [boostcampwm-2022/web05-SleepyWoods#124]
## 💁 설명

제목 그대로 입니다 ...
토큰이 없는데, 데이터를 받아오고 있습니다 !

- 이슈 발견 위치
main 페이지 -> /signup 진입 -> 뒤로가기 (main으로 돌아감)

```ts
// frontend code

const { data } = await axios.get('/api/user/auth');
console.log(data);

const nickname = data.nickname?.trim();
const hair = data.characterName?.trim();
console.log(nickname, hair);
```

![image](https://user-images.githubusercontent.com/63227474/205447076-c908b63f-305a-4fd0-98fa-feb192209dfe.png)
![image](https://user-images.githubusercontent.com/63227474/205447089-47bde590-97e6-4684-a25d-61ea095802ef.png)

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- 왜...이러는건데요....흑흑

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

**Comment by hj1n** [comment]
nginx 캐시 설정으로 해결
