### ISSUE TITLE
카카오 소셜 로그인 Signup 오류 해결

### ISSUE THREAD

**Issue by comeintostout** [boostcampwm-2022/web05-SleepyWoods#142]
## 💁 설명

- 현재 카카오 소셜 로그인 signup 안되는 상태.
- DB 저장이 안되는 것으로 보아, signup API 가 문제인 것으로 추측.
- 카카오 userId 가 숫자로 이루어진 문자열인데, typeORM 에서 이를 number로 받아들이는 것 같음.

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- [x] signup API 수정
- [x] kakao userId 문자열로 강제 변환.

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 없음.

**Comment by hj1n** [comment]
Backend 수정완료
Frontend 에서는 원래대로 API요청해주시면 됩니다~~

**Comment by comeintostout** [comment]
- #110 
- 해당 부분에서 나온 error와 원인 같음.
- typeORM 에서 number로만 된 string 값을 저장 시, 중간에 오류가 생기는 것으로 판별. (save 등 조회 시 못 찾음)
- 카카오 userId 에 'k' 값을 맨 앞에 붙혀 강제로 문자열로 변환 해결
