### ISSUE TITLE
[problem] 회원가입한 유저가 입장 시 제대로 랜더링되지 않는 문제

### ISSUE THREAD

**Issue by JJongBin** [boostcampwm-2022/web05-SleepyWoods#151]
## 💁 설명

- 회원가입한 유저가 입장 시 제대로 랜더링되지 않는 문제
- 콘솔로 찍어보니 새로 가입한 유저의 닉네임, 헤어의 정보를 받아오지 못함

**Comment by comeintostout** [comment]
카카오 소셜 로그인 기능이 미흡하여 생긴 일.
서버 DB에는 k로 시작하는 userId로 저장되어 있으나, 토큰에는 k없이 조회한 정보로 들어가있어
가입한 유저라도 임시 accessToken(nickname, characterName 없음)을 발급 받은 것.
