### ISSUE TITLE
CORS 에러

### ISSUE THREAD

**Issue by comeintostout** [boostcampwm-2022/web05-SleepyWoods#27]
## 💁 설명

- 서버 쪽에서 CORS 설정 안해줘서 생긴 에러.

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- `localhost:5173`에 대하여 CORS 설정 완료

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- FRONT_URI 수정 시 .env에 반영 필수

**Comment by ktmihs** [comment]
### cors 에러 해결 중 직면한 문제
![image](https://user-images.githubusercontent.com/63227474/202107037-2b5a9c70-bdd2-4873-9049-d6f7cce718d9.png)

💬 서버에서 네이버로 리다이렉션이 아닌 겟 요청을 보내면서 생긴 문제라고 생각
