### ISSUE TITLE
phaser 화면 크기 문제

### ISSUE THREAD

**Issue by ktmihs** [boostcampwm-2022/web05-SleepyWoods#36]
## 💁 설명
모여봐요 위치: town 페이지
모여봐요 문제: phaser 화면 크기가 작아진 페이지에서의 크기 그대로 유지되는 문제 발견
   화면을 다시 키워도 작아진 phaser 화면은 커지지 않는 문제...
   + 비율이 유지되어 하단 여백이 생김

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

- 당장 모여봐요

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 두 문제 모두 테스트 해보기

**Comment by JJongBin** [comment]
phaser config의 내용을 수정하여 해결

```js
scale: {
    mode: Phaser.Scale.RESIZE,
...
}
```
