### ISSUE TITLE
[SleepyBoard] 게시글 조회

### ISSUE THREAD

**Issue by comeintostout** [boostcampwm-2022/web05-SleepyWoods#50]
## 💁 설명

- SleepyBoard의 게시글 조회를 위한 구조와 API를 만든다.

## 📑 체크리스트

> 구현해야하는 이슈 체크리스트

### FE
- [x] SleepyBoard 시작 버튼을 만들어서 API 요청을 보내기.

### BE
- [x] Board DB에서 List 반환 하는 API 만들기
- [x] Following, Follower 시스템 및 나의 글 보기 등의 Filter 기능도 고려하자.

## 🚧 주의 사항

> 이슈를 구현할 때 유의깊게 살펴볼 사항

- 권한을 확인하자.
- 필터 기능을 고려하자

**Comment by hj1n** [comment]
- like 필드 포함 안된 것 수정 필요
